### ISSUE TITLE
[Bug] highlight group not found: TabbyHl___

### ISSUE THREAD

**Issue by luiz00martins** [nanozuki/tabby.nvim#59]
I'm getting an error when starting tabby:

```
Error detected while processing function TabbyTabline:                                                                                          
line    1:                                                                                                                                      
E5108: Error executing lua ...packer/start/tabby.nvim/lua/tabby/internal/highlight.lua:29: Vim(highlight):E411: highlight group not found: TabbyHl___                                                                                                                                           
stack traceback:                                                                                                                                
        [C]: in function 'cmd'                                                                                                                  
        ...packer/start/tabby.nvim/lua/tabby/internal/highlight.lua:29: in function 'register'                                                  
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:93: in function 'highlight'                                                 
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:67: in function 'frag'                                                      
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:24: in function 'node'                                                      
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:65: in function
<...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:57>                                                                                                                                            
        vim/shared.lua: in function 'tbl_map'                                                                                                   
        .../site/pack/packer/start/tabby.nvim/lua/tabby/tabline.lua:146: in function 'update'                                                   
        [string "luaeval()"]:1: in main chunk
```

It's quite inconsistent. It only happens on some startups, in others it just runs fine (feels like 50/50 chance). When the error happens, the tabline does not load correctly. Here's some screenshots of how the tab normally looks like, and how it looks like with the error:
![normal](https://user-images.githubusercontent.com/43142209/169822413-c900bb41-85e1-4c0e-b953-bc70c22fc04e.png)
![buggy](https://user-images.githubusercontent.com/43142209/169822442-b2dbd838-d9e5-43b7-8db9-178ad313564a.png)

This is my full config:
```lua
local filename = require('tabby.filename')
local util = require('tabby.util')

local hl_tabline = util.extract_nvim_hl('TabLine')
local hl_tabline_sel = util.extract_nvim_hl('TabLineSel')
local hl_tabline_fill = util.extract_nvim_hl('TabLineFill')

local function tab_label(tabid, active)
	local icon = active and '' or ''
	local number = vim.api.nvim_tabpage_get_number(tabid)
local name = util.get_tab_name(tabid)
	if active then
		return string.format(' %s %d: %s ', icon, number, name)
	else
		return string.format(' %s %d ', icon, number)
	end
end

local tabline = {
	hl = 'TabLineFill',
	layout = 'tab_only',
	head = {
		{ '  ', hl = { fg = hl_tabline.fg, bg = hl_tabline.bg } },
		{ '', hl = { fg = hl_tabline.bg, bg = hl_tabline_fill.bg } },
	},
	active_tab = {
		label = function(tabid)
			return {
				tab_label(tabid, true),
				hl = { fg = hl_tabline_sel.fg, bg = hl_tabline_sel.bg, style = 'bold' },
			}
		end,
		left_sep = { '', hl = { fg = hl_tabline_sel.bg, bg = hl_tabline_fill.bg } },
		right_sep = { '', hl = { fg = hl_tabline_sel.bg, bg = hl_tabline_fill.bg } },
	},
	inactive_tab = {
		label = function(tabid)
			return {
				tab_label(tabid, false),
				hl = { fg = hl_tabline.fg, bg = hl_tabline.bg, style = 'bold' },
			}
		end,
		left_sep = { '', hl = { fg = hl_tabline_fill.bg, bg = hl_tabline_fill.bg } },
		right_sep = { '', hl = { fg = hl_tabline_fill.bg, bg = hl_tabline_fill.bg } },
	},
	top_win = {
		label = function(winid)
			return {
				--' > ' .. filename.unique(winid) .. ' ',
				'',
				hl = 'TabLine',
			}
		end,
		left_sep = { ' ', hl = 'TabLineFill' },
	},
	win = {
		label = function(winid)
			return {
				--' - ' .. filename.unique(winid) .. ' ',
				'',
				hl = 'TabLine',
			}
		end,
		left_sep = { ' ', hl = 'TabLineFill' },
	},
}

require('tabby').setup({
	tabline = tabline,
})
```

**Comment by luiz00martins** [comment]
In case you cannot repro...

### Debugging info
With this config, the plugin works, but the colors are inconsistent:
```lua
local filename = require('tabby.filename')
local util = require('tabby.util')

local hl_tabline = util.extract_nvim_hl('TabLine')
local hl_tabline_sel = util.extract_nvim_hl('TabLineSel')
local hl_tabline_fill = util.extract_nvim_hl('TabLineFill')

local function tab_label(tabid, active)
	local icon = active and '' or ''
	local number = vim.api.nvim_tabpage_get_number(tabid)
	local name = util.get_tab_name(tabid)
	if active then
		return string.format(' %s %d: %s ', icon, number, name)
	else
		return string.format(' %s %d ', icon, number)
	end
end

local tabline = {
	hl = 'TabLineFill',
	layout = 'tab_only',
	-- REMOVED HEAD
	active_tab = {
		label = function(tabid)
			return {
				tab_label(tabid, true),
				hl = { fg = hl_tabline_sel.fg, bg = hl_tabline_sel.bg, style = 'bold' },
			}
			-- REMOVED SEP
		end,
	},
	inactive_tab = {
		label = function(tabid)
			return {
				tab_label(tabid, false),
				hl = { fg = hl_tabline.fg, bg = hl_tabline.bg, style = 'bold' },
			}
			-- REMOVED SEP
		end,
	},
	top_win = {
		label = function(winid)
			return {
				--' > ' .. filename.unique(winid) .. ' ',
				'',
				hl = 'TabLine',
			}
		end,
		left_sep = { ' ', hl = 'TabLineFill' },
	},
	win = {
		label = function(winid)
			return {
				--' - ' .. filename.unique(winid) .. ' ',
				'',
				hl = 'TabLine',
			}
		end,
		left_sep = { ' ', hl = 'TabLineFill' },
	},
}

require('tabby').setup({
	tabline = tabline,
})
```
![normal_color](https://user-images.githubusercontent.com/43142209/169829483-09203d14-4c4e-415d-b48c-a17dc61f95fb.png)
![weird_color](https://user-images.githubusercontent.com/43142209/169829516-b38387aa-5f57-4b10-9cb2-02e5f0222ef0.png)

Same results (inconsistent colors) with this simpler one:
```lua
local filename = require('tabby.filename')
local util = require('tabby.util')

local hl_tabline = util.extract_nvim_hl('TabLine')
local hl_tabline_sel = util.extract_nvim_hl('TabLineSel')
local hl_tabline_fill = util.extract_nvim_hl('TabLineFill')

local function tab_label(tabid, active)
	local icon = active and '' or ''
	local number = vim.api.nvim_tabpage_get_number(tabid)
	local name = util.get_tab_name(tabid)
	if active then
		return string.format(' %s %d: %s ', icon, number, name)
	else
		return string.format(' %s %d ', icon, number)
	end
end

local tabline = {
	hl = 'TabLineFill',
	layout = 'tab_only',
	active_tab = {
		label = function(tabid)
			return {
				tab_label(tabid, true),
				hl = { fg = hl_tabline_sel.fg, bg = hl_tabline_sel.bg, style = 'bold' },
			}
		end,
	},
}

require('tabby').setup({
	tabline = tabline,
})

```

However, more bizarrely, if I complete remove all options, the error returns. The config below yields the error again:
```lua
require('tabby').setup({})
```

**Comment by nanozuki** [comment]
Thanks for your feedback, I will do some tests in this week.

**Comment by yitsushi** [comment]
Note: It was introduced somewhere in the the commits on May/10 or May/11, I last synced around end of April, today I synced plugins and it's there.

**Comment by yitsushi** [comment]
Went through the commits one by one and called `PackerUpdate`, the first commit where I can see the error: https://github.com/nanozuki/tabby.nvim/commit/7866ad70f87293ab64bf443c61f38c695b7f3a78

**Comment by nanozuki** [comment]
@yitsushi After I read the code, I think maybe this is the bug I fixed in the latest commit. May you try the latest commit and test it again?

**Comment by moevis** [comment]
I got the same problem with latest code.

I just use default config likes following:

```
require"tabby".setup({})
```

and here is the output:

```
line    1:
E5108: Error executing lua ...packer/start/tabby.nvim/lua/tabby/internal/highlight.lua:29: Vim(highlight):E411: highlight group not found: TabbyHl___
stack traceback:
        [C]: in function 'cmd'
        ...packer/start/tabby.nvim/lua/tabby/internal/highlight.lua:29: in function 'register'
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:93: in function 'highlight'
        ...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:67: in function <...ck/packer/start/tabby.nvim/lua/tabby/internal/render.lua:57>
        vim/shared.lua: in function 'tbl_map'
        .../site/pack/packer/start/tabby.nvim/lua/tabby/tabline.lua:146: in function 'update'
        [string "luaeval()"]:1: in main chunk
```


In addtion, when I initialized the plugin without a map param

```
require"tabby".setup()
```

I got these error:

```
Error detected while processing /Users/bytedance/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_extend'
        ...vim/site/pack/packer/start/tabby.nvim/lua/tabby/init.lua:14: in function 'setup'
        /Users/bytedance/.config/nvim/init.lua:572: in main chunk
```

My neovim version is

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1650023513425.local

on macOS 12.4

**Comment by moevis** [comment]
After I tried several presets, I found this config seems to have no error throwed.

```
require"tabby".setup({
    tabline = require("tabby.presets").tab_with_top_win,
})
```

But the apperance is strange:

<img width="491" alt="Screen Shot 2022-05-30 at 16 33 23" src="https://user-images.githubusercontent.com/3747445/170952013-ae03d8b5-1108-4f7b-b6ad-661cb3f76fd3.png">


Following presets will throw error: highlight group not found: TabbyHl___

```
active_wins_at_tail
active_tab_with_wins
tab_only
```

**Comment by nanozuki** [comment]
I fixed it; I used the wrong way to get Highlight. If there are more compatibility issues, welcome to tell me.

**Comment by luiz00martins** [comment]
Yep the `TabbyHl__` error is gone!

I'm still getting the wrong highlight sometimes though. Same error as I mentioned in my "debugging info". Sometimes I get the right highlight, sometimes it uses a (wrong) gray color. Here's an example with my full config (in the original answer):
![Screenshot from 2022-06-01 11-55-02](https://user-images.githubusercontent.com/43142209/171434981-8761c6b7-c865-4e21-a073-977e7e8ee520.png)
![Screenshot from 2022-06-01 11-55-41](https://user-images.githubusercontent.com/43142209/171434994-40cdcbd3-1e5d-4e03-a6b6-a473a93f3a9d.png)

The chances of this happening looks exactly like the chances of me getting the original one, about 50/50.

Also these were mutually exclusive. By that I mean that, depending on the config, I would either get one, or the other (i.e. they would replace one another). So, I have high suspicions that these two are related.

**Comment by anstadnik** [comment]
I can confirm wrong highlights
![image](https://user-images.githubusercontent.com/40110937/171446043-d0ada4b5-06a2-4c4e-ab20-052c337103b1.png)

**Comment by nanozuki** [comment]
@luiz00martins One scenario I've found that causes this is the order in which tabby and theme are launched. May you use packer, try to use the `after` option as a workaround? I would to explore a nice way to improve this.

**Comment by nanozuki** [comment]
@anstadnik Oh, May you tell me what theme you use?

**Comment by anstadnik** [comment]
@nanozuki sure :)

<details>
  <summary>minimal init.lua</summary>
  
```lua
vim.g.python3_host_prog = '/home/astadnik/.virtualenvs/neovim/bin/python3'

local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.termopen(('git clone --depth 1 https://github.com/wbthomason/packer.nvim %q'):format(install_path))
end


require('packer').startup({ function(use)
  use { 'rmehri01/onenord.nvim', config = [[require 'plugins.onenord']] }
  use { "nanozuki/tabby.nvim",
    config = [[require("tabby").setup({ tabline = require("tabby.presets").active_tab_with_wins })]] }
end})

% vim.o.background='light'
```
  
</details>
The error occurs when changing the background, and sometimes persists (maybe when multiple nvim instances are opened)

**Comment by anstadnik** [comment]
Oh you maybe would want to see `onenord.lua`.

<details>
<summary>onenord.lua</summary>

```lua
-- Colorscheme
require('onenord').setup({
	fade_nc = true, -- Fade non-current windows, making them more distinguishable
	-- Style that is applied to various groups: see `highlight-args` for options
	styles = {
		comments = "italic",
		strings = "italic",
		keywords = "bold",
		functions = "NONE",
		variables = "NONE",
		diagnostics = "undercurl",
	},
	disable = {
		background = false, -- Disable setting the background color
		cursorline = false, -- Disable the cursorline
		eob_lines = true, -- Hide the end-of-buffer lines
	},
	-- Inverse highlight for different groups
	inverse = {
		match_paren = true,
	},
})
```

</details>

**Comment by luiz00martins** [comment]
> @luiz00martins One scenario I've found that causes this is the order in which tabby and theme are launched. May you use packer, try to use the `after` option as a workaround? I would to explore a nice way to improve this.

Tried it, with no luck. Got the same problem with the following `use` clause:
```lua
use {
	'nanozuki/tabby.nvim',
	after = 'folke/tokyonight.nvim',
}
```

**Comment by nanozuki** [comment]
@luiz00martins What about your whole config, including the plugin manager's setting? Do you put the config of `tabby.nvim` in the packer's plugin declaration? Like this:

```lua
use {
  'nanozuki/tabby.nvim',
  config = function()
    require('tabby').setup({})
  end
}
```

**Comment by luiz00martins** [comment]
I already showed my whole tabby config, it's in the original issue (and it's definetely being called). My *whole* config is... hundreds of lines long.

And I'd love to debug it more, but I'm being blocked by #64

**Comment by nanozuki** [comment]
The key point of this question is:

The sentence `local hl_tabline = util.extract_nvim_hl('TabLine')` should be called after theme loaded. If not, you will get the wrong color. Mentions, not the tabby should be loaded after the theme, is this `util.extract_nvim_hl` should be called after the theme is loaded.

This is why I need the whole neovim config if I want to figure out the problem. If you use packer, you should add config to the plugin declaration, so packer will confirm the config runner after the plugin is loaded. It will delay the calling of function `util.extract_nvim_hl`.

If your config is too large, you can try to write a minimal config to reproduce it.

**Comment by luiz00martins** [comment]
>The sentence local `hl_tabline = util.extract_nvim_hl('TabLine')` should be called after theme loaded. If not, you will get the wrong color.

That's it! Making sure that runs after setting the colorscheme fixes the problem. Thanks.

If tabby currently pulls in "hard values" from the colorscheme, maybe linking to the HL group instead could fix this behaviour.

**Comment by nanozuki** [comment]
Because the separator's highlight is calculated from two highlights, I can't link directly. I'm exploring a new way to get highlights.

**Comment by anstadnik** [comment]
Am I understanding correctly that the current approach won't allow theme or (more importantly background) change while nvim is already running?

**Comment by nanozuki** [comment]
> Am I understanding correctly that the current approach won't allow theme or (more importantly background) change while nvim is already running?

For current preset configs, it is. I'm writing the next version of tabby, It has a better way to automatically handle color scheme changing.
